name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches:
      - main   # or 'master' if your repo uses that
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: |
          bundle install

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --destination ./_site

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v2   # ✅ no deprecation
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
